CREATE DATABASE IF NOT EXISTS crud_php;
USE crud_php;

CREATE TABLE IF NOT EXISTS produits (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nom VARCHAR(100) NOT NULL,
  quantite INT NOT NULL,
  prix DECIMAL(10,2) NOT NULL
);
